// For Capstone Engine. AUTO-GENERATED FILE, DO NOT EDIT
package capstone

import capstone.Sparc_const

object Sparc_const {
    // Enums corresponding to Sparc condition codes, both icc's and fcc's.
    const val SPARC_CC_INVALID = 0

    // Integer condition codes
    const val SPARC_CC_ICC_A = 8 + 256
    const val SPARC_CC_ICC_N = 0 + 256
    const val SPARC_CC_ICC_NE = 9 + 256
    const val SPARC_CC_ICC_E = 1 + 256
    const val SPARC_CC_ICC_G = 10 + 256
    const val SPARC_CC_ICC_LE = 2 + 256
    const val SPARC_CC_ICC_GE = 11 + 256
    const val SPARC_CC_ICC_L = 3 + 256
    const val SPARC_CC_ICC_GU = 12 + 256
    const val SPARC_CC_ICC_LEU = 4 + 256
    const val SPARC_CC_ICC_CC = 13 + 256
    const val SPARC_CC_ICC_CS = 5 + 256
    const val SPARC_CC_ICC_POS = 14 + 256
    const val SPARC_CC_ICC_NEG = 6 + 256
    const val SPARC_CC_ICC_VC = 15 + 256
    const val SPARC_CC_ICC_VS = 7 + 256

    // Floating condition codes
    const val SPARC_CC_FCC_A = 8 + 16 + 256
    const val SPARC_CC_FCC_N = 0 + 16 + 256
    const val SPARC_CC_FCC_U = 7 + 16 + 256
    const val SPARC_CC_FCC_G = 6 + 16 + 256
    const val SPARC_CC_FCC_UG = 5 + 16 + 256
    const val SPARC_CC_FCC_L = 4 + 16 + 256
    const val SPARC_CC_FCC_UL = 3 + 16 + 256
    const val SPARC_CC_FCC_LG = 2 + 16 + 256
    const val SPARC_CC_FCC_NE = 1 + 16 + 256
    const val SPARC_CC_FCC_E = 9 + 16 + 256
    const val SPARC_CC_FCC_UE = 10 + 16 + 256
    const val SPARC_CC_FCC_GE = 11 + 16 + 256
    const val SPARC_CC_FCC_UGE = 12 + 16 + 256
    const val SPARC_CC_FCC_LE = 13 + 16 + 256
    const val SPARC_CC_FCC_ULE = 14 + 16 + 256
    const val SPARC_CC_FCC_O = 15 + 16 + 256

    // Branch hint
    const val SPARC_HINT_INVALID = 0
    const val SPARC_HINT_A = 1 shl 0
    const val SPARC_HINT_PT = 1 shl 1
    const val SPARC_HINT_PN = 1 shl 2

    // Operand type for instruction's operands
    const val SPARC_OP_INVALID = 0
    const val SPARC_OP_REG = 1
    const val SPARC_OP_IMM = 2
    const val SPARC_OP_MEM = 3

    // SPARC registers
    const val SPARC_REG_INVALID = 0
    const val SPARC_REG_F0 = 1
    const val SPARC_REG_F1 = 2
    const val SPARC_REG_F2 = 3
    const val SPARC_REG_F3 = 4
    const val SPARC_REG_F4 = 5
    const val SPARC_REG_F5 = 6
    const val SPARC_REG_F6 = 7
    const val SPARC_REG_F7 = 8
    const val SPARC_REG_F8 = 9
    const val SPARC_REG_F9 = 10
    const val SPARC_REG_F10 = 11
    const val SPARC_REG_F11 = 12
    const val SPARC_REG_F12 = 13
    const val SPARC_REG_F13 = 14
    const val SPARC_REG_F14 = 15
    const val SPARC_REG_F15 = 16
    const val SPARC_REG_F16 = 17
    const val SPARC_REG_F17 = 18
    const val SPARC_REG_F18 = 19
    const val SPARC_REG_F19 = 20
    const val SPARC_REG_F20 = 21
    const val SPARC_REG_F21 = 22
    const val SPARC_REG_F22 = 23
    const val SPARC_REG_F23 = 24
    const val SPARC_REG_F24 = 25
    const val SPARC_REG_F25 = 26
    const val SPARC_REG_F26 = 27
    const val SPARC_REG_F27 = 28
    const val SPARC_REG_F28 = 29
    const val SPARC_REG_F29 = 30
    const val SPARC_REG_F30 = 31
    const val SPARC_REG_F31 = 32
    const val SPARC_REG_F32 = 33
    const val SPARC_REG_F34 = 34
    const val SPARC_REG_F36 = 35
    const val SPARC_REG_F38 = 36
    const val SPARC_REG_F40 = 37
    const val SPARC_REG_F42 = 38
    const val SPARC_REG_F44 = 39
    const val SPARC_REG_F46 = 40
    const val SPARC_REG_F48 = 41
    const val SPARC_REG_F50 = 42
    const val SPARC_REG_F52 = 43
    const val SPARC_REG_F54 = 44
    const val SPARC_REG_F56 = 45
    const val SPARC_REG_F58 = 46
    const val SPARC_REG_F60 = 47
    const val SPARC_REG_F62 = 48
    const val SPARC_REG_FCC0 = 49
    const val SPARC_REG_FCC1 = 50
    const val SPARC_REG_FCC2 = 51
    const val SPARC_REG_FCC3 = 52
    const val SPARC_REG_FP = 53
    const val SPARC_REG_G0 = 54
    const val SPARC_REG_G1 = 55
    const val SPARC_REG_G2 = 56
    const val SPARC_REG_G3 = 57
    const val SPARC_REG_G4 = 58
    const val SPARC_REG_G5 = 59
    const val SPARC_REG_G6 = 60
    const val SPARC_REG_G7 = 61
    const val SPARC_REG_I0 = 62
    const val SPARC_REG_I1 = 63
    const val SPARC_REG_I2 = 64
    const val SPARC_REG_I3 = 65
    const val SPARC_REG_I4 = 66
    const val SPARC_REG_I5 = 67
    const val SPARC_REG_I7 = 68
    const val SPARC_REG_ICC = 69
    const val SPARC_REG_L0 = 70
    const val SPARC_REG_L1 = 71
    const val SPARC_REG_L2 = 72
    const val SPARC_REG_L3 = 73
    const val SPARC_REG_L4 = 74
    const val SPARC_REG_L5 = 75
    const val SPARC_REG_L6 = 76
    const val SPARC_REG_L7 = 77
    const val SPARC_REG_O0 = 78
    const val SPARC_REG_O1 = 79
    const val SPARC_REG_O2 = 80
    const val SPARC_REG_O3 = 81
    const val SPARC_REG_O4 = 82
    const val SPARC_REG_O5 = 83
    const val SPARC_REG_O7 = 84
    const val SPARC_REG_SP = 85
    const val SPARC_REG_Y = 86
    const val SPARC_REG_XCC = 87
    const val SPARC_REG_ENDING = 88
    const val SPARC_REG_O6 = SPARC_REG_SP
    const val SPARC_REG_I6 = SPARC_REG_FP

    // SPARC instruction
    const val SPARC_INS_INVALID = 0
    const val SPARC_INS_ADDCC = 1
    const val SPARC_INS_ADDX = 2
    const val SPARC_INS_ADDXCC = 3
    const val SPARC_INS_ADDXC = 4
    const val SPARC_INS_ADDXCCC = 5
    const val SPARC_INS_ADD = 6
    const val SPARC_INS_ALIGNADDR = 7
    const val SPARC_INS_ALIGNADDRL = 8
    const val SPARC_INS_ANDCC = 9
    const val SPARC_INS_ANDNCC = 10
    const val SPARC_INS_ANDN = 11
    const val SPARC_INS_AND = 12
    const val SPARC_INS_ARRAY16 = 13
    const val SPARC_INS_ARRAY32 = 14
    const val SPARC_INS_ARRAY8 = 15
    const val SPARC_INS_B = 16
    const val SPARC_INS_JMP = 17
    const val SPARC_INS_BMASK = 18
    const val SPARC_INS_FB = 19
    const val SPARC_INS_BRGEZ = 20
    const val SPARC_INS_BRGZ = 21
    const val SPARC_INS_BRLEZ = 22
    const val SPARC_INS_BRLZ = 23
    const val SPARC_INS_BRNZ = 24
    const val SPARC_INS_BRZ = 25
    const val SPARC_INS_BSHUFFLE = 26
    const val SPARC_INS_CALL = 27
    const val SPARC_INS_CASX = 28
    const val SPARC_INS_CAS = 29
    const val SPARC_INS_CMASK16 = 30
    const val SPARC_INS_CMASK32 = 31
    const val SPARC_INS_CMASK8 = 32
    const val SPARC_INS_CMP = 33
    const val SPARC_INS_EDGE16 = 34
    const val SPARC_INS_EDGE16L = 35
    const val SPARC_INS_EDGE16LN = 36
    const val SPARC_INS_EDGE16N = 37
    const val SPARC_INS_EDGE32 = 38
    const val SPARC_INS_EDGE32L = 39
    const val SPARC_INS_EDGE32LN = 40
    const val SPARC_INS_EDGE32N = 41
    const val SPARC_INS_EDGE8 = 42
    const val SPARC_INS_EDGE8L = 43
    const val SPARC_INS_EDGE8LN = 44
    const val SPARC_INS_EDGE8N = 45
    const val SPARC_INS_FABSD = 46
    const val SPARC_INS_FABSQ = 47
    const val SPARC_INS_FABSS = 48
    const val SPARC_INS_FADDD = 49
    const val SPARC_INS_FADDQ = 50
    const val SPARC_INS_FADDS = 51
    const val SPARC_INS_FALIGNDATA = 52
    const val SPARC_INS_FAND = 53
    const val SPARC_INS_FANDNOT1 = 54
    const val SPARC_INS_FANDNOT1S = 55
    const val SPARC_INS_FANDNOT2 = 56
    const val SPARC_INS_FANDNOT2S = 57
    const val SPARC_INS_FANDS = 58
    const val SPARC_INS_FCHKSM16 = 59
    const val SPARC_INS_FCMPD = 60
    const val SPARC_INS_FCMPEQ16 = 61
    const val SPARC_INS_FCMPEQ32 = 62
    const val SPARC_INS_FCMPGT16 = 63
    const val SPARC_INS_FCMPGT32 = 64
    const val SPARC_INS_FCMPLE16 = 65
    const val SPARC_INS_FCMPLE32 = 66
    const val SPARC_INS_FCMPNE16 = 67
    const val SPARC_INS_FCMPNE32 = 68
    const val SPARC_INS_FCMPQ = 69
    const val SPARC_INS_FCMPS = 70
    const val SPARC_INS_FDIVD = 71
    const val SPARC_INS_FDIVQ = 72
    const val SPARC_INS_FDIVS = 73
    const val SPARC_INS_FDMULQ = 74
    const val SPARC_INS_FDTOI = 75
    const val SPARC_INS_FDTOQ = 76
    const val SPARC_INS_FDTOS = 77
    const val SPARC_INS_FDTOX = 78
    const val SPARC_INS_FEXPAND = 79
    const val SPARC_INS_FHADDD = 80
    const val SPARC_INS_FHADDS = 81
    const val SPARC_INS_FHSUBD = 82
    const val SPARC_INS_FHSUBS = 83
    const val SPARC_INS_FITOD = 84
    const val SPARC_INS_FITOQ = 85
    const val SPARC_INS_FITOS = 86
    const val SPARC_INS_FLCMPD = 87
    const val SPARC_INS_FLCMPS = 88
    const val SPARC_INS_FLUSHW = 89
    const val SPARC_INS_FMEAN16 = 90
    const val SPARC_INS_FMOVD = 91
    const val SPARC_INS_FMOVQ = 92
    const val SPARC_INS_FMOVRDGEZ = 93
    const val SPARC_INS_FMOVRQGEZ = 94
    const val SPARC_INS_FMOVRSGEZ = 95
    const val SPARC_INS_FMOVRDGZ = 96
    const val SPARC_INS_FMOVRQGZ = 97
    const val SPARC_INS_FMOVRSGZ = 98
    const val SPARC_INS_FMOVRDLEZ = 99
    const val SPARC_INS_FMOVRQLEZ = 100
    const val SPARC_INS_FMOVRSLEZ = 101
    const val SPARC_INS_FMOVRDLZ = 102
    const val SPARC_INS_FMOVRQLZ = 103
    const val SPARC_INS_FMOVRSLZ = 104
    const val SPARC_INS_FMOVRDNZ = 105
    const val SPARC_INS_FMOVRQNZ = 106
    const val SPARC_INS_FMOVRSNZ = 107
    const val SPARC_INS_FMOVRDZ = 108
    const val SPARC_INS_FMOVRQZ = 109
    const val SPARC_INS_FMOVRSZ = 110
    const val SPARC_INS_FMOVS = 111
    const val SPARC_INS_FMUL8SUX16 = 112
    const val SPARC_INS_FMUL8ULX16 = 113
    const val SPARC_INS_FMUL8X16 = 114
    const val SPARC_INS_FMUL8X16AL = 115
    const val SPARC_INS_FMUL8X16AU = 116
    const val SPARC_INS_FMULD = 117
    const val SPARC_INS_FMULD8SUX16 = 118
    const val SPARC_INS_FMULD8ULX16 = 119
    const val SPARC_INS_FMULQ = 120
    const val SPARC_INS_FMULS = 121
    const val SPARC_INS_FNADDD = 122
    const val SPARC_INS_FNADDS = 123
    const val SPARC_INS_FNAND = 124
    const val SPARC_INS_FNANDS = 125
    const val SPARC_INS_FNEGD = 126
    const val SPARC_INS_FNEGQ = 127
    const val SPARC_INS_FNEGS = 128
    const val SPARC_INS_FNHADDD = 129
    const val SPARC_INS_FNHADDS = 130
    const val SPARC_INS_FNOR = 131
    const val SPARC_INS_FNORS = 132
    const val SPARC_INS_FNOT1 = 133
    const val SPARC_INS_FNOT1S = 134
    const val SPARC_INS_FNOT2 = 135
    const val SPARC_INS_FNOT2S = 136
    const val SPARC_INS_FONE = 137
    const val SPARC_INS_FONES = 138
    const val SPARC_INS_FOR = 139
    const val SPARC_INS_FORNOT1 = 140
    const val SPARC_INS_FORNOT1S = 141
    const val SPARC_INS_FORNOT2 = 142
    const val SPARC_INS_FORNOT2S = 143
    const val SPARC_INS_FORS = 144
    const val SPARC_INS_FPACK16 = 145
    const val SPARC_INS_FPACK32 = 146
    const val SPARC_INS_FPACKFIX = 147
    const val SPARC_INS_FPADD16 = 148
    const val SPARC_INS_FPADD16S = 149
    const val SPARC_INS_FPADD32 = 150
    const val SPARC_INS_FPADD32S = 151
    const val SPARC_INS_FPADD64 = 152
    const val SPARC_INS_FPMERGE = 153
    const val SPARC_INS_FPSUB16 = 154
    const val SPARC_INS_FPSUB16S = 155
    const val SPARC_INS_FPSUB32 = 156
    const val SPARC_INS_FPSUB32S = 157
    const val SPARC_INS_FQTOD = 158
    const val SPARC_INS_FQTOI = 159
    const val SPARC_INS_FQTOS = 160
    const val SPARC_INS_FQTOX = 161
    const val SPARC_INS_FSLAS16 = 162
    const val SPARC_INS_FSLAS32 = 163
    const val SPARC_INS_FSLL16 = 164
    const val SPARC_INS_FSLL32 = 165
    const val SPARC_INS_FSMULD = 166
    const val SPARC_INS_FSQRTD = 167
    const val SPARC_INS_FSQRTQ = 168
    const val SPARC_INS_FSQRTS = 169
    const val SPARC_INS_FSRA16 = 170
    const val SPARC_INS_FSRA32 = 171
    const val SPARC_INS_FSRC1 = 172
    const val SPARC_INS_FSRC1S = 173
    const val SPARC_INS_FSRC2 = 174
    const val SPARC_INS_FSRC2S = 175
    const val SPARC_INS_FSRL16 = 176
    const val SPARC_INS_FSRL32 = 177
    const val SPARC_INS_FSTOD = 178
    const val SPARC_INS_FSTOI = 179
    const val SPARC_INS_FSTOQ = 180
    const val SPARC_INS_FSTOX = 181
    const val SPARC_INS_FSUBD = 182
    const val SPARC_INS_FSUBQ = 183
    const val SPARC_INS_FSUBS = 184
    const val SPARC_INS_FXNOR = 185
    const val SPARC_INS_FXNORS = 186
    const val SPARC_INS_FXOR = 187
    const val SPARC_INS_FXORS = 188
    const val SPARC_INS_FXTOD = 189
    const val SPARC_INS_FXTOQ = 190
    const val SPARC_INS_FXTOS = 191
    const val SPARC_INS_FZERO = 192
    const val SPARC_INS_FZEROS = 193
    const val SPARC_INS_JMPL = 194
    const val SPARC_INS_LDD = 195
    const val SPARC_INS_LD = 196
    const val SPARC_INS_LDQ = 197
    const val SPARC_INS_LDSB = 198
    const val SPARC_INS_LDSH = 199
    const val SPARC_INS_LDSW = 200
    const val SPARC_INS_LDUB = 201
    const val SPARC_INS_LDUH = 202
    const val SPARC_INS_LDX = 203
    const val SPARC_INS_LZCNT = 204
    const val SPARC_INS_MEMBAR = 205
    const val SPARC_INS_MOVDTOX = 206
    const val SPARC_INS_MOV = 207
    const val SPARC_INS_MOVRGEZ = 208
    const val SPARC_INS_MOVRGZ = 209
    const val SPARC_INS_MOVRLEZ = 210
    const val SPARC_INS_MOVRLZ = 211
    const val SPARC_INS_MOVRNZ = 212
    const val SPARC_INS_MOVRZ = 213
    const val SPARC_INS_MOVSTOSW = 214
    const val SPARC_INS_MOVSTOUW = 215
    const val SPARC_INS_MULX = 216
    const val SPARC_INS_NOP = 217
    const val SPARC_INS_ORCC = 218
    const val SPARC_INS_ORNCC = 219
    const val SPARC_INS_ORN = 220
    const val SPARC_INS_OR = 221
    const val SPARC_INS_PDIST = 222
    const val SPARC_INS_PDISTN = 223
    const val SPARC_INS_POPC = 224
    const val SPARC_INS_RD = 225
    const val SPARC_INS_RESTORE = 226
    const val SPARC_INS_RETT = 227
    const val SPARC_INS_SAVE = 228
    const val SPARC_INS_SDIVCC = 229
    const val SPARC_INS_SDIVX = 230
    const val SPARC_INS_SDIV = 231
    const val SPARC_INS_SETHI = 232
    const val SPARC_INS_SHUTDOWN = 233
    const val SPARC_INS_SIAM = 234
    const val SPARC_INS_SLLX = 235
    const val SPARC_INS_SLL = 236
    const val SPARC_INS_SMULCC = 237
    const val SPARC_INS_SMUL = 238
    const val SPARC_INS_SRAX = 239
    const val SPARC_INS_SRA = 240
    const val SPARC_INS_SRLX = 241
    const val SPARC_INS_SRL = 242
    const val SPARC_INS_STBAR = 243
    const val SPARC_INS_STB = 244
    const val SPARC_INS_STD = 245
    const val SPARC_INS_ST = 246
    const val SPARC_INS_STH = 247
    const val SPARC_INS_STQ = 248
    const val SPARC_INS_STX = 249
    const val SPARC_INS_SUBCC = 250
    const val SPARC_INS_SUBX = 251
    const val SPARC_INS_SUBXCC = 252
    const val SPARC_INS_SUB = 253
    const val SPARC_INS_SWAP = 254
    const val SPARC_INS_TADDCCTV = 255
    const val SPARC_INS_TADDCC = 256
    const val SPARC_INS_T = 257
    const val SPARC_INS_TSUBCCTV = 258
    const val SPARC_INS_TSUBCC = 259
    const val SPARC_INS_UDIVCC = 260
    const val SPARC_INS_UDIVX = 261
    const val SPARC_INS_UDIV = 262
    const val SPARC_INS_UMULCC = 263
    const val SPARC_INS_UMULXHI = 264
    const val SPARC_INS_UMUL = 265
    const val SPARC_INS_UNIMP = 266
    const val SPARC_INS_FCMPED = 267
    const val SPARC_INS_FCMPEQ = 268
    const val SPARC_INS_FCMPES = 269
    const val SPARC_INS_WR = 270
    const val SPARC_INS_XMULX = 271
    const val SPARC_INS_XMULXHI = 272
    const val SPARC_INS_XNORCC = 273
    const val SPARC_INS_XNOR = 274
    const val SPARC_INS_XORCC = 275
    const val SPARC_INS_XOR = 276
    const val SPARC_INS_RET = 277
    const val SPARC_INS_RETL = 278
    const val SPARC_INS_ENDING = 279

    // Group of SPARC instructions
    const val SPARC_GRP_INVALID = 0

    // Generic groups
    const val SPARC_GRP_JUMP = 1

    // Architecture-specific groups
    const val SPARC_GRP_HARDQUAD = 128
    const val SPARC_GRP_V9 = 129
    const val SPARC_GRP_VIS = 130
    const val SPARC_GRP_VIS2 = 131
    const val SPARC_GRP_VIS3 = 132
    const val SPARC_GRP_32BIT = 133
    const val SPARC_GRP_64BIT = 134
    const val SPARC_GRP_ENDING = 135
}